#!/usr/bin/env python3
"""Fetch SED-ML + SBML protocols from sys-bio/temp-biomodels, pinned to a commit.

Downloads the curated simulation protocols (and the SBML they were authored
against) from the temp-biomodels paper (PMC12677764) into data/sedml_source/.
These files specify time horizons, solver tolerances, and outputs for BioModels
SBML parity testing.

The corpus (~49 MB) is gitignored and reconstructed locally by this script; only
the textual provenance manifest (``temp_biomodels_manifest.json``, generated by
``generate_sedml_manifest.py``) enters git. To make "reproduce our numbers"
deterministic, this fetch is **pinned to an exact upstream commit** — a re-run
after temp-biomodels' ``main`` moves still gives the identical bytes, and the
``--verify-manifest`` pass asserts every referenced file's sha256 matches.

Modes:
    (default)          check out the pinned commit (PINNED_COMMIT); reproducible.
    --commit <sha>     pin to a different commit.
    --upstream-latest  clone main's tip instead (refresh/extend; WARNS re: drift,
                       and the manifest verification will flag any changed bytes).

Usage:
    python fetch_sedml.py [--dest data/sedml_source] [--commit <sha>]
    python fetch_sedml.py --upstream-latest        # refresh against main (unpinned)
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_URL = "https://github.com/sys-bio/temp-biomodels.git"
# Pinned upstream commit — the rr_parity ODE corpus was built against this.
# Keep in lockstep with generate_sedml_manifest.py's PINNED_COMMIT and the
# committed temp_biomodels_manifest.json upstream_pin.
PINNED_COMMIT = "6a09daf46af1bb89e4857436b623a7b8720863ad"

HERE = Path(__file__).resolve().parent
DEFAULT_DEST = HERE / "data" / "sedml_source"
DEFAULT_MANIFEST = HERE / "temp_biomodels_manifest.json"


def _run(cmd: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True)


def verify_manifest(dest_final: Path, manifest_path: Path) -> int:
    """Assert every manifest file's sha256 matches the fetched bytes. Returns #mismatches."""
    manifest = json.loads(manifest_path.read_text())
    records = manifest["records"]
    mismatch = missing = 0
    for r in records:
        # manifest paths are 'final/<id>'; dest_final already points at .../final
        rel = r["id"]
        f = dest_final / rel
        if not f.is_file():
            missing += 1
            if missing <= 10:
                print(f"  MISSING: {rel}", file=sys.stderr)
            continue
        got = hashlib.sha256(f.read_bytes()).hexdigest()
        if got != r["sha256"]:
            mismatch += 1
            if mismatch <= 10:
                print(
                    f"  DRIFT: {rel}\n    manifest {r['sha256']}\n    fetched  {got}",
                    file=sys.stderr,
                )
    total = len(records)
    ok = total - mismatch - missing
    print(f"\nmanifest verify : {ok}/{total} match  (mismatch={mismatch}, missing={missing})")
    return mismatch + missing


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--dest", type=Path, default=DEFAULT_DEST, help="destination directory")
    ap.add_argument(
        "--commit",
        default=PINNED_COMMIT,
        help=f"upstream commit to pin (default {PINNED_COMMIT[:12]})",
    )
    ap.add_argument(
        "--upstream-latest",
        action="store_true",
        help="clone main's tip instead of the pin (refresh/extend; unpinned, warns re: drift)",
    )
    ap.add_argument(
        "--manifest", type=Path, default=DEFAULT_MANIFEST, help="manifest to verify against"
    )
    ap.add_argument(
        "--no-verify", action="store_true", help="skip the post-fetch manifest verification"
    )
    args = ap.parse_args()

    if args.dest.exists() and any(args.dest.iterdir()):
        print(f"Destination {args.dest} already exists and is not empty.")
        response = input("Remove and re-download? [y/N]: ")
        if response.lower() != "y":
            print("Aborted.")
            return 1
        shutil.rmtree(args.dest)

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir) / "temp-biomodels"

        if args.upstream_latest:
            print(
                "WARNING: --upstream-latest fetches main's tip — NOT reproducible; "
                "the manifest verification will flag any drift from the pin.",
                file=sys.stderr,
            )
            print("Cloning sys-bio/temp-biomodels @ main (shallow)...")
            r = _run(
                [
                    "git",
                    "clone",
                    "--filter=blob:none",
                    "--depth",
                    "1",
                    "--branch",
                    "main",
                    REPO_URL,
                    str(tmp_path),
                ]
            )
            if r.returncode != 0:
                print(f"Git clone failed:\n{r.stderr}", file=sys.stderr)
                return 1
        else:
            print(f"Cloning sys-bio/temp-biomodels @ {args.commit[:12]} (pinned)...")
            # Blob-filtered, no-checkout clone, then check out the exact commit.
            r = _run(
                ["git", "clone", "--filter=blob:none", "--no-checkout", REPO_URL, str(tmp_path)]
            )
            if r.returncode != 0:
                print(f"Git clone failed:\n{r.stderr}", file=sys.stderr)
                return 1
            r = _run(["git", "-C", str(tmp_path), "checkout", args.commit])
            if r.returncode != 0:
                print(f"Checkout of {args.commit} failed:\n{r.stderr}", file=sys.stderr)
                return 1
            head = _run(["git", "-C", str(tmp_path), "rev-parse", "HEAD"]).stdout.strip()
            print(f"  checked out {head[:12]}")

        src_final = tmp_path / "final"
        if not src_final.exists():
            print("Error: 'final/' directory not found in cloned repo", file=sys.stderr)
            return 1

        print(f"Copying to {args.dest}...")
        args.dest.mkdir(parents=True, exist_ok=True)
        dest_final = args.dest / "final"
        shutil.copytree(src_final, dest_final)

        for doc in ["README.md", "LICENSE"]:
            src_doc = tmp_path / doc
            if src_doc.exists():
                shutil.copy2(src_doc, args.dest / doc)

    dest_final = args.dest / "final"
    n_models = len(list(dest_final.iterdir())) if dest_final.exists() else 0
    n_sedml = len(list(dest_final.rglob("*.sedml"))) if dest_final.exists() else 0
    total_size = sum(f.stat().st_size for f in dest_final.rglob("*") if f.is_file())

    print("\n✓ fetch complete")
    print(f"  Location: {args.dest}")
    print(f"  Pin: {'main (unpinned)' if args.upstream_latest else args.commit}")
    print(f"  Models: {n_models}   SED-ML files: {n_sedml}   Size: {total_size / 1e6:.1f} MB")

    rc = 0
    if not args.no_verify and args.manifest.exists():
        drift = verify_manifest(dest_final, args.manifest)
        if drift:
            print(
                "Corpus does NOT match the pinned manifest (see DRIFT/MISSING above).",
                file=sys.stderr,
            )
            rc = 1
    elif not args.no_verify:
        print(f"(no manifest at {args.manifest}; skipping verification)")

    print("\nNext: run materialize.py to populate models/ directory")
    return rc


if __name__ == "__main__":
    sys.exit(main())
