#!/usr/bin/env python3
"""Materialize the rr_parity model tree from the job manifests.

Lays out one directory per model so a SED-ML file resolves its ``<model
source=...>`` against the SBML sitting beside it:

    models/<model_id>/<sbml_basename>.xml      (BioModels SBML)
    models/<model_id>/<sedml_basename>.sedml   (temp-biomodels SED-ML, if any)

Both the SED-ML protocols (curated from the temp-biomodels paper, PMC12677764,
~49 MB) and the SBML (full BioModels keep-set, ~270 MB) are GITIGNORED and
regenerated by this script from local sources, so neither enters git history.
(See models/.gitignore.)

Sources (override via env):
    temp-biomodels SED-ML+SBML  $BIOMODELS_SEDML_DIR
        default <repo>/bngsim/parity_checks/rr_parity/data/sedml_source/final
        (fetch with fetch_sedml.py from sys-bio/temp-biomodels, PMC12677764)
    plain BioModels SBML        $BIOMODELS_SBML_DIR
        default <repo>/bngsim/benchmarks/suites/biomodels/data/sbml_downloads
        (fetch with ../../benchmarks/suites/biomodels/fetch.py)

Usage:
    python materialize.py [--jobs ode_jobs.json] [--dest models] \
                          [--sedml-only] [--dry-run]
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]  # repo root (bngsim/)

DEFAULT_SEDML_DIR = Path(
    os.environ.get(
        "BIOMODELS_SEDML_DIR",
        HERE / "data" / "sedml_source" / "final",
    )
)
DEFAULT_SBML_DIR = Path(
    os.environ.get(
        "BIOMODELS_SBML_DIR",
        REPO / "benchmarks" / "suites" / "biomodels" / "data" / "sbml_downloads",
    )
)

# Committed canonical-SBML overrides for models whose upstream source is bad and
# would otherwise reconstruct WRONG: BIOMD0000000883's temp-biomodels mirror ships
# a COPASI export (not SBML), and 14 others had empty BioModels downloads. These
# small files (~1 MB, in git despite the corpus being gitignored) are copied LAST,
# so a fresh rebuild is correct regardless of the upstream source. See the dir's
# README. (fetch.py is also hardened to re-fetch empty/invalid files; this is the
# no-network guarantee.)
OVERRIDES_DIR = HERE / "data" / "sbml_overrides"


def resolve(job: dict, sedml_dir: Path, sbml_dir: Path) -> tuple[Path | None, Path | None]:
    """Return (sbml_src, sedml_src) for a job, or None where unavailable."""
    mid = job["model_id"]
    params = job.get("params", {})
    # Extract sbml basename from model path
    model_path = Path(job["model"])
    sbml_basename = model_path.name

    if params.get("sbml_origin") == "temp-biomodels":
        sbml = sedml_dir / mid / sbml_basename
    else:
        sbml = sbml_dir / f"{mid}.xml"
    sedml = sedml_dir / mid / params["sedml"] if params.get("sedml") else None
    return (sbml if sbml.exists() else None), (sedml if sedml and sedml.exists() else None)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--jobs", type=Path, default=HERE / "ode_jobs.json")
    ap.add_argument("--dest", type=Path, default=HERE / "models")
    ap.add_argument("--sedml-dir", type=Path, default=DEFAULT_SEDML_DIR)
    ap.add_argument("--sbml-dir", type=Path, default=DEFAULT_SBML_DIR)
    ap.add_argument(
        "--sedml-only", action="store_true", help="Only place SED-ML (the committed set)"
    )
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    jobs = json.loads(args.jobs.read_text())["jobs"]
    n_sbml = n_sedml = sbml_miss = sedml_miss = 0
    sbml_bytes = sedml_bytes = 0

    for job in jobs:
        mid = job["model_id"]
        sbml_src, sedml_src = resolve(job, args.sedml_dir, args.sbml_dir)
        mdir = args.dest / mid

        if sedml_src is not None:
            if not args.dry_run:
                mdir.mkdir(parents=True, exist_ok=True)
                shutil.copy2(sedml_src, mdir / sedml_src.name)
            n_sedml += 1
            sedml_bytes += sedml_src.stat().st_size
        elif job.get("params", {}).get("sedml"):
            sedml_miss += 1

        if not args.sedml_only:
            if sbml_src is not None:
                if not args.dry_run:
                    mdir.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(sbml_src, mdir / sbml_src.name)
                n_sbml += 1
                sbml_bytes += sbml_src.stat().st_size
            else:
                sbml_miss += 1

    # Apply committed SBML overrides LAST so they win over a bad upstream source
    # (see OVERRIDES_DIR). Each data/sbml_overrides/<id>/<file>.xml is copied to
    # models/<id>/<file>.xml — the exact path the manifest expects.
    n_override = 0
    if not args.sedml_only and OVERRIDES_DIR.is_dir():
        for ov_dir in sorted(p for p in OVERRIDES_DIR.iterdir() if p.is_dir()):
            for ov_file in sorted(ov_dir.glob("*.xml")):
                dest = args.dest / ov_dir.name / ov_file.name
                if not args.dry_run:
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(ov_file, dest)
                n_override += 1

    print(f"jobs            : {len(jobs)}")
    print(
        f"SED-ML placed   : {n_sedml}  ({sedml_bytes / 1e6:.1f} MB, gitignored)  missing={sedml_miss}"
    )
    if not args.sedml_only:
        print(f"SBML overrides  : {n_override} applied (committed, data/sbml_overrides/)")
    if not args.sedml_only:
        print(
            f"SBML placed     : {n_sbml}  ({sbml_bytes / 1e6:.1f} MB, gitignored)  missing={sbml_miss}"
        )
    if args.dry_run:
        print("(dry run — nothing written)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
